/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendorRouteRouteImport } from './routes/_app/vendor/route'
import { Route as AppVendorOpportunitiesRouteImport } from './routes/_app/vendor/opportunities'
import { Route as AppVendorLedgerRouteImport } from './routes/_app/vendor/ledger'
import { Route as AppVendorBidRouteImport } from './routes/_app/vendor/bid'
import { Route as AppConsumerNewJobRouteImport } from './routes/_app/consumer/new-job'
import { Route as AppConsumerMaterialsRouteImport } from './routes/_app/consumer/materials'
import { Route as AppConsumerEscrowRouteImport } from './routes/_app/consumer/escrow'
import { Route as AppConsumerDisputeRouteImport } from './routes/_app/consumer/dispute'
import { Route as AppConsumerDashboardRouteImport } from './routes/_app/consumer/dashboard'
import { Route as AppConsumerBidsRouteImport } from './routes/_app/consumer/bids'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorRouteRoute = AppVendorRouteRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorOpportunitiesRoute = AppVendorOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppVendorRouteRoute,
} as any)
const AppVendorLedgerRoute = AppVendorLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppVendorRouteRoute,
} as any)
const AppVendorBidRoute = AppVendorBidRouteImport.update({
  id: '/bid',
  path: '/bid',
  getParentRoute: () => AppVendorRouteRoute,
} as any)
const AppConsumerNewJobRoute = AppConsumerNewJobRouteImport.update({
  id: '/consumer/new-job',
  path: '/consumer/new-job',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumerMaterialsRoute = AppConsumerMaterialsRouteImport.update({
  id: '/consumer/materials',
  path: '/consumer/materials',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumerEscrowRoute = AppConsumerEscrowRouteImport.update({
  id: '/consumer/escrow',
  path: '/consumer/escrow',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumerDisputeRoute = AppConsumerDisputeRouteImport.update({
  id: '/consumer/dispute',
  path: '/consumer/dispute',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumerDashboardRoute = AppConsumerDashboardRouteImport.update({
  id: '/consumer/dashboard',
  path: '/consumer/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumerBidsRoute = AppConsumerBidsRouteImport.update({
  id: '/consumer/bids',
  path: '/consumer/bids',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vendor': typeof AppVendorRouteRouteWithChildren
  '/consumer/bids': typeof AppConsumerBidsRoute
  '/consumer/dashboard': typeof AppConsumerDashboardRoute
  '/consumer/dispute': typeof AppConsumerDisputeRoute
  '/consumer/escrow': typeof AppConsumerEscrowRoute
  '/consumer/materials': typeof AppConsumerMaterialsRoute
  '/consumer/new-job': typeof AppConsumerNewJobRoute
  '/vendor/bid': typeof AppVendorBidRoute
  '/vendor/ledger': typeof AppVendorLedgerRoute
  '/vendor/opportunities': typeof AppVendorOpportunitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vendor': typeof AppVendorRouteRouteWithChildren
  '/consumer/bids': typeof AppConsumerBidsRoute
  '/consumer/dashboard': typeof AppConsumerDashboardRoute
  '/consumer/dispute': typeof AppConsumerDisputeRoute
  '/consumer/escrow': typeof AppConsumerEscrowRoute
  '/consumer/materials': typeof AppConsumerMaterialsRoute
  '/consumer/new-job': typeof AppConsumerNewJobRoute
  '/vendor/bid': typeof AppVendorBidRoute
  '/vendor/ledger': typeof AppVendorLedgerRoute
  '/vendor/opportunities': typeof AppVendorOpportunitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/vendor': typeof AppVendorRouteRouteWithChildren
  '/_app/consumer/bids': typeof AppConsumerBidsRoute
  '/_app/consumer/dashboard': typeof AppConsumerDashboardRoute
  '/_app/consumer/dispute': typeof AppConsumerDisputeRoute
  '/_app/consumer/escrow': typeof AppConsumerEscrowRoute
  '/_app/consumer/materials': typeof AppConsumerMaterialsRoute
  '/_app/consumer/new-job': typeof AppConsumerNewJobRoute
  '/_app/vendor/bid': typeof AppVendorBidRoute
  '/_app/vendor/ledger': typeof AppVendorLedgerRoute
  '/_app/vendor/opportunities': typeof AppVendorOpportunitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vendor'
    | '/consumer/bids'
    | '/consumer/dashboard'
    | '/consumer/dispute'
    | '/consumer/escrow'
    | '/consumer/materials'
    | '/consumer/new-job'
    | '/vendor/bid'
    | '/vendor/ledger'
    | '/vendor/opportunities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/vendor'
    | '/consumer/bids'
    | '/consumer/dashboard'
    | '/consumer/dispute'
    | '/consumer/escrow'
    | '/consumer/materials'
    | '/consumer/new-job'
    | '/vendor/bid'
    | '/vendor/ledger'
    | '/vendor/opportunities'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/vendor'
    | '/_app/consumer/bids'
    | '/_app/consumer/dashboard'
    | '/_app/consumer/dispute'
    | '/_app/consumer/escrow'
    | '/_app/consumer/materials'
    | '/_app/consumer/new-job'
    | '/_app/vendor/bid'
    | '/_app/vendor/ledger'
    | '/_app/vendor/opportunities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendor': {
      id: '/_app/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AppVendorRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/opportunities': {
      id: '/_app/vendor/opportunities'
      path: '/opportunities'
      fullPath: '/vendor/opportunities'
      preLoaderRoute: typeof AppVendorOpportunitiesRouteImport
      parentRoute: typeof AppVendorRouteRoute
    }
    '/_app/vendor/ledger': {
      id: '/_app/vendor/ledger'
      path: '/ledger'
      fullPath: '/vendor/ledger'
      preLoaderRoute: typeof AppVendorLedgerRouteImport
      parentRoute: typeof AppVendorRouteRoute
    }
    '/_app/vendor/bid': {
      id: '/_app/vendor/bid'
      path: '/bid'
      fullPath: '/vendor/bid'
      preLoaderRoute: typeof AppVendorBidRouteImport
      parentRoute: typeof AppVendorRouteRoute
    }
    '/_app/consumer/new-job': {
      id: '/_app/consumer/new-job'
      path: '/consumer/new-job'
      fullPath: '/consumer/new-job'
      preLoaderRoute: typeof AppConsumerNewJobRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumer/materials': {
      id: '/_app/consumer/materials'
      path: '/consumer/materials'
      fullPath: '/consumer/materials'
      preLoaderRoute: typeof AppConsumerMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumer/escrow': {
      id: '/_app/consumer/escrow'
      path: '/consumer/escrow'
      fullPath: '/consumer/escrow'
      preLoaderRoute: typeof AppConsumerEscrowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumer/dispute': {
      id: '/_app/consumer/dispute'
      path: '/consumer/dispute'
      fullPath: '/consumer/dispute'
      preLoaderRoute: typeof AppConsumerDisputeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumer/dashboard': {
      id: '/_app/consumer/dashboard'
      path: '/consumer/dashboard'
      fullPath: '/consumer/dashboard'
      preLoaderRoute: typeof AppConsumerDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumer/bids': {
      id: '/_app/consumer/bids'
      path: '/consumer/bids'
      fullPath: '/consumer/bids'
      preLoaderRoute: typeof AppConsumerBidsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppVendorRouteRouteChildren {
  AppVendorBidRoute: typeof AppVendorBidRoute
  AppVendorLedgerRoute: typeof AppVendorLedgerRoute
  AppVendorOpportunitiesRoute: typeof AppVendorOpportunitiesRoute
}

const AppVendorRouteRouteChildren: AppVendorRouteRouteChildren = {
  AppVendorBidRoute: AppVendorBidRoute,
  AppVendorLedgerRoute: AppVendorLedgerRoute,
  AppVendorOpportunitiesRoute: AppVendorOpportunitiesRoute,
}

const AppVendorRouteRouteWithChildren = AppVendorRouteRoute._addFileChildren(
  AppVendorRouteRouteChildren,
)

interface AppRouteChildren {
  AppVendorRouteRoute: typeof AppVendorRouteRouteWithChildren
  AppConsumerBidsRoute: typeof AppConsumerBidsRoute
  AppConsumerDashboardRoute: typeof AppConsumerDashboardRoute
  AppConsumerDisputeRoute: typeof AppConsumerDisputeRoute
  AppConsumerEscrowRoute: typeof AppConsumerEscrowRoute
  AppConsumerMaterialsRoute: typeof AppConsumerMaterialsRoute
  AppConsumerNewJobRoute: typeof AppConsumerNewJobRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppVendorRouteRoute: AppVendorRouteRouteWithChildren,
  AppConsumerBidsRoute: AppConsumerBidsRoute,
  AppConsumerDashboardRoute: AppConsumerDashboardRoute,
  AppConsumerDisputeRoute: AppConsumerDisputeRoute,
  AppConsumerEscrowRoute: AppConsumerEscrowRoute,
  AppConsumerMaterialsRoute: AppConsumerMaterialsRoute,
  AppConsumerNewJobRoute: AppConsumerNewJobRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
