/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppNewJobRouteImport } from './routes/_app/new-job'
import { Route as AppEscrowRouteImport } from './routes/_app/escrow'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBidsRouteImport } from './routes/_app/bids'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNewJobRoute = AppNewJobRouteImport.update({
  id: '/new-job',
  path: '/new-job',
  getParentRoute: () => AppRoute,
} as any)
const AppEscrowRoute = AppEscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBidsRoute = AppBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bids': typeof AppBidsRoute
  '/dashboard': typeof AppDashboardRoute
  '/escrow': typeof AppEscrowRoute
  '/new-job': typeof AppNewJobRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bids': typeof AppBidsRoute
  '/dashboard': typeof AppDashboardRoute
  '/escrow': typeof AppEscrowRoute
  '/new-job': typeof AppNewJobRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/bids': typeof AppBidsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/escrow': typeof AppEscrowRoute
  '/_app/new-job': typeof AppNewJobRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bids' | '/dashboard' | '/escrow' | '/new-job'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bids' | '/dashboard' | '/escrow' | '/new-job'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/bids'
    | '/_app/dashboard'
    | '/_app/escrow'
    | '/_app/new-job'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/new-job': {
      id: '/_app/new-job'
      path: '/new-job'
      fullPath: '/new-job'
      preLoaderRoute: typeof AppNewJobRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escrow': {
      id: '/_app/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof AppEscrowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bids': {
      id: '/_app/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof AppBidsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBidsRoute: typeof AppBidsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEscrowRoute: typeof AppEscrowRoute
  AppNewJobRoute: typeof AppNewJobRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBidsRoute: AppBidsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEscrowRoute: AppEscrowRoute,
  AppNewJobRoute: AppNewJobRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
